version: '3.8'

services:
  web:
    container_name: hackathon-web
    build: .
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8800:8800"
    environment:
      - ENVIRONMENT=local
      - WATCHFILES_FORCE_POLLING=true
      - POSTGRES_HOST=fiap-local-development-db-1
      - POSTGRES_DATABASE_NAME=fiap_db_hackathon
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./:/build


networks:
  default:
    external: true
    name: fiap-local-development-network