apiVersion: v1
kind: Service
metadata:
  name: fiap-hackathon
  namespace: fiap-hackathon
spec:
  selector:
    app: fiap-hackathon
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer