"""add_enrollment_and_password_to_user_table

Revision ID: ecd580f989fc
Revises: 53c8fa3f4148
Create Date: 2024-03-23 15:41:13.670830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd580f989fc'
down_revision = '53c8fa3f4148'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('enrollment', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_users_enrollment'), 'users', ['enrollment'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_enrollment'), table_name='users')
    op.drop_column('users', 'password')
    op.drop_column('users', 'enrollment')
    # ### end Alembic commands ###
