"""create_records_table

Revision ID: 766148aed658
Revises: bbac4c99a800
Create Date: 2024-03-22 00:26:43.042757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766148aed658'
down_revision = 'bbac4c99a800'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ref_datetime', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_records_user_id_users'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records'))
    )
    op.create_index(op.f('ix_records_user_id'), 'records', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_work_email'), 'users', ['work_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_work_email'), table_name='users')
    op.drop_index(op.f('ix_records_user_id'), table_name='records')
    op.drop_table('records')
    # ### end Alembic commands ###
